name: deploy-container

# workflow starts when ...
on:
  # code is pushed ...
  push:
    # to the master branch ...
    branches:
      - master
    # inside the container app
    paths:
      - 'packages/container/**'

# set execution environment to inside container directory
defaults:
  run:
    working-directory: packages/container

jobs:
  # build and deploy project
  build:
    # pick virtual machine
    runs-on: ubuntu-latest
    steps:
      # load code into VM environment
      - uses: actions/checkout@v2
      # install dependencies
      - run: npm install
      # webpack build
      - run: npm run build
      # get access to AWS CLI
      - uses: shinyinc/action-aws-cli@v1.2
      # use AWS CLI's s3 feature to sync contents of dist directory with specified S3 bucket
      # ${{ }} are encrypted secrets set on github
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        # access key and secret key are essentially username and password for AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
